export const SUB_CATEGORIES = [
  {
    title: 'mobiles',
    items: [
      {
        id: 1,
        name: 'Apple iPhone 13 Pro',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/617bdedb-2aae-4fd9-b6bc-707d7489f3b622241421_182x182.jpg',
        description: "Built-in GPS, GLONASS, Galileo, QZSS and BeiDou, Digital compass, iBeacon micro-location.",
        price: 91800,
      },
      {
        id: 2,
        name: 'Apple iPhone 12',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/61b46b57-002a-4620-baaa-e3f624eaea1e22241350_182x182.jpg',
        description: "Fast-charge capable: Up to 50% charge in 30 minutes11 with 20W adapter or higher (sold separately",
        price: 53300,
      },
      {
        id: 3,
        name: 'Apple iPhone 11',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/77a3883c-2699-4082-a6d1-9812df54372a22241350_182x182.jpg',
        description: "Video playback:Up to 17 hours Video playback (streamed):Up to 10 hours Audio playback:Up to 65 hours Charging via USB to computer system or power adapterCharging via USB to computer system or power adapter",
        price: 35500,
      },
      {
        id: 4,
        name: 'Redmi 10A Sport',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/67729b73-cbc5-4571-b1e8-4c60d2383f0b22120613_182x182.jpg',
        description: "Redmi, DBG Technology (India) Pvt Ltd , PLOT NO-2, BAWAL, SECTOR-8, Rewari, Haryana, 123501.",
        price: 10500,
      },
      {
        id: 5,
        name: 'Apple iPad Pro 11',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/e25f7044-9841-4e94-b188-300c03cf6f3e23110756_182x182.jpg',
        description: "Specifications Of Open Box (Demo Unit) Apple iPad Pro 11 inch (2018) 64 GB Wi-Fi (Silver)",
        price: 18800,
      },
      {
        id: 6,
        name: 'Samsung A13',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/3e740092-a349-4e3f-adb4-dccb802dcb3722251010_182x182.jpg',
        description: "The 2MP Depth Camera lets you adjust the depth of field in your photos. With a simple touch, you can easily fine-tune the background blur behind your subject for high-quality portrait shots that truly stand out.",
        price: 14000,
      },
      {
        id: 7,
        name: 'OnePlus 11 5G',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/51aa1812-92d8-468a-8fee-3baef262d86723081012_182x182.jpg',
        description: "Touch Response Rate: Up to 1000 Hz Support sRGB, Display P3, 10-bit Color Depth Cover Glass: Corning® Gorilla® Glass Victus Nature tone display",
        price: 60000,
      },
      {
        id: 8,
        name: 'Apple iPhone 13 Pro Max',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/e6d390ff-dfc9-488e-8978-85e9cc29dbb522241401_182x182.jpg',
        description: "iPhone 13 Pro and iPhone 13 Pro Max are not compatible with existing micro-SIM cards",
        price: 95500,
      },
    ],
  },
  {
    title: 'bikes',
    items: [
      {
        id: 1,
        name: 'Yamaha',
        imageUrl: 'https://bd.gaadicdn.com/processedimages/yamaha/mt-15-2-0/source/mt-15-2-062e4b1d700b63.jpg?tr=w-375',
        description: "BRAND NEW KIDS BIKE AND SCOOTERS READY FOR SHIPMENT.",
        price: 18000,
      },
      {
        id: 2,
        name: 'Apache RTR',
        imageUrl: 'https://bd.gaadicdn.com/processedimages/hero-motocorp/hero-motocorp-splendor/640X309/hero-motocorp-splendor628c6c03932f2.jpg',
        description: "Just 1 year old bike for sale due to relocation.",
        price: 120000,
      },
      {
        id: 3,
        name: 'Kawasaki Ninja',
        imageUrl: 'https://bd.gaadicdn.com/processedimages/kawasaki/ninja-400/640X309/ninja-40062b2b760470d9.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 150000,
      },
      {
        id: 4,
        name: 'BMW',
        imageUrl: 'https://bd.gaadicdn.com/processedimages/suzuki/hayabusa/640X309/hayabusa614d56bddfc73.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 2500000,
      },
    ],
  },
  {
    title: 'electronics-applicances',
    items: [
      {
        id: 1,
        name: 'Samsung 32 80 T4900 HD Ready Smart LED TV',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/cc766645-e2ff-437f-a41e-d396021372e8_182x182.jpg',
        description: "Specifications Of Samsung 32 inch (80cm) Series 4 Smart HD Ready LED TV with Multiple Voice Assistant UA32T4900 (2021 Model Edition)",
        price: 23000,
      },
      {
        id: 2,
        name: 'Samsung 198 Litres 3 Star Direct Cool Single Door Refrigerator',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/7c6fc29c-cad4-4549-8731-a8d583a2f1eb22131116_182x182.jpg',
        description: "Enjoy quick and intuitive control with the Digi-Touch Cool™ control panel. With a simple touch, select the Power Cool Mode to rapidly cool food and drinks or choose the e-Defrost option to effortlessly de-frost the freezer. It also helps save energy with Eco Mode and a Door Alarm. It even alerts you about power cuts and restores any temperature loss*.",
        price: 18000,
      },
      {
        id: 3,
        name: 'Samsung 6.5 Kg 5 Star Fully Automatic Front Load Inverter Washing Machine',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/b6f3839b-10ba-42fc-a135-51f858ca263a21301017_182x182.jpg',
        description: "Specifications Of Samsung 6.5 Kg 5 Star Fully Automatic Front Load Inverter Washing Machine with Hygiene Steam Technology (WW66R22EK0S, Silver).",
        price: 350000,
      },
      {
        id: 4,
        name: 'Whirlpool 265 Litres 2 Star Frost Free Double Door Refrigerator',
        imageUrl: 'https://d2xamzlzrdbdbn.cloudfront.net/products/04772827-3b8e-436e-9d7d-2930558d6921_182x182.jpg',
        description: "Scientifically designed air tower and strategically placed vents that let out cool and fresh air into different sections of the refrigerator providing uniform cooling for long lasting freshness.",
        price: 25000,
      },
    ],
  },
  {
    title: 'furniture',
    items: [
      {
        id: 1,
        name: 'Sofa',
        imageUrl: 'https://ii2.pepperfry.com/media/catalog/product/c/a/494x544/calleros-chaise-lounger-in-chestnut-brown-colour-by-casacraft-calleros-chaise-lounger-in-chestnut-br-jxdvoe.jpg',
        description: "CasaCraft offers the best in comfort, with elan. The collection consists of a series of modern designs, which are simple yet striking and represent the ideals of minimalism and cutting excess. As a perfect blend of functionality and exceptional aesthetics, each piece is crafted with passion and reflects high quality and style.",
        price: 36000,
      },
      {
        id: 2,
        name: 'Mayur Sheesham Wood Queen Size Bed In Honey Oak Finish',
        imageUrl: 'https://ii2.pepperfry.com/media/catalog/product/e/l/494x544/eloa-queen-size-bed-with-upholstered-headboard-and-storage-in-columbia-walnut-finish-by-casacraft-el-r5ssrm.jpg',
        description: "CasaCraft offers the best in comfort, with elan. The collection consists of a series of modern designs, which are simple yet striking and represent the ideals of minimalism and cutting excess. As a perfect blend of functionality and exceptional aesthetics, each piece is crafted with passion and reflects high quality and style.",
        price: 18000,
      },
      {
        id: 3,
        name: 'Haruka 6 Seater Dining Set in Walnut & Sky Blue Finish',
        imageUrl: 'https://ii3.pepperfry.com/media/catalog/product/h/a/494x544/haruka-6-seater-dining-set-in-walnut---sky-blue-finish-by-casacraft-haruka-6-seater-dining-set-in-wa-9vbvhl.jpg',
        description: "Accessories shown in the image are only for representation and are not part of the product.Depending on your screen settings and resolution on your device there may be a slight variance in fabric color and wood polish of the image and actual product.Wood grains will vary from product to product in case of solid wood furniture.Furniture having intricate hand-painted details are individual unique pieces and may have slight distinctions and variance between the picture and actual product.The Primary material is the main material used to manufacture the product and in addition to the primary material there might also be other type of materials used in the manufacturing of the product.",
        price: 35000,
      },
      {
        id: 4,
        name: 'Omura Hutch Table With Cabinets In Dark Brown Finish',
        imageUrl: 'https://ii2.pepperfry.com/media/catalog/product/o/m/494x544/omura-study-table-with-cabinets-in-dark-brown-finish-by-mintwud-omura-study-table-with-cabinets-in-d-o01jym.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 7000,
      },
    ],
  },
  {
    title: 'fashion',
    items: [
      {
        id: 1,
        name: 'Men Striped Long Sleeves Slim Fit Smart Casual Shirt',
        imageUrl: 'https://lmsin.net/cdn-cgi/image/h=493,w=333,q=60,fit=cover/https://aaeff43fe32172cbcecc-ae2a4e9a8cbc330ede5588dedf56886e.lmsin.net/max/1000012005319-Blue-MIDBLUE-1000012005319_01-2100.jpg',
        description: "Let your comfort and style pop out with this striped casual shirt. It features a spread collar, long sleeves, and a button placket that is a perfect addition to your casual wardrobe. Make your outfit look perfect by teaming it up with a pair of casual trousers and lace-up shoes.",
        price: 2500,
      },
      {
        id: 2,
        name: 'Women Striped Medium Crop Sweater',
        imageUrl: 'https://lmsin.net/cdn-cgi/image/h=345,w=345,q=60,fit=cover/https://aaeff43fe32172cbcecc-ae2a4e9a8cbc330ede5588dedf56886e.lmsin.net/max/1000011469025-Blue-BLUE-1000011469025_01-2100.jpg',
        description: "Beat the winter blues in this sweater which is crafted in a cropped length with a striped pattern. It is styled with a mock neckline, drop shoulders, long sleeves, and ribbed trim. Team up this sweater with jeans and sneakers to stay cosy and chic.",
        price: 1800,
      },
      {
        id: 3,
        name: 'Women Placement Border Printed Button Down A-line Dress',
        imageUrl: 'https://lmsin.net/cdn-cgi/image/h=493,w=333,q=60,fit=cover/https://aaeff43fe32172cbcecc-ae2a4e9a8cbc330ede5588dedf56886e.lmsin.net/max/1000012206803-Pink-MAGENTA-1000012206803_01-2100.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 1500,
      },
      {
        id: 4,
        name: 'Men Colourblocked Slim Fit T-shirt',
        imageUrl: 'https://lmsin.net/cdn-cgi/image/h=345,w=345,q=60,fit=cover/https://aaeff43fe32172cbcecc-ae2a4e9a8cbc330ede5588dedf56886e.lmsin.net/max/1000012208713-Pink-PINK-1000012208713_01-2100.jpg',
        description: "Elevate your sporty style in this T-shirt. It has a typographic print, a colourblocked design, a crew neck, and short sleeves to accentuate your look. Pair this tee with tapered joggers and high-top sneakers for an elevated look.",
        price: 2500,
      },
    ],
  },
  {
    title: 'books',
    items: [
      {
        id: 1,
        name: 'Final Offer',
        imageUrl: 'https://cdn01.sapnaonline.com/product_media/9780349433479/md_9780349433479_020220231356355.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 500,
      },
      {
        id: 2,
        name: 'Lockwood & Co',
        imageUrl: 'https://cdn01.sapnaonline.com/product_media/9780241613122/md_9780241613122_250120231346179.jpg',
        description: "by Jonathan Stroud (Author), Penguin (Publisher).",
        price: 383,
      },
      {
        id: 3,
        name: 'Friends With Benefits : The India Us Story',
        imageUrl: 'https://cdn01.sapnaonline.com/product_media/9789356295902/md_9789356295902_060220231214079.jpg',
        description: "About the Book : Friends with Benefits: The India-US Story Thirty years ago, when veteran journalist Seema Sirohi first arrived in Washington DC, bilateral relations between India and the United States of America were at their worst. In the late 1980s and 1990s, the political spotlight shone favourably upon Pakistan and China. For the leader of the free world, India didnt matter. The years leading up to the twenty-first century saw the US-and the multilateral organizations of which it was a member-force India to jump through endless bureaucratic hoops. Indias nuclear tests in 1998 were the final nail in its coffin, as far as the.",
        price: 600,
      },
      {
        id: 4,
        name: 'Badass Habits : Cultivate The Awareness Boundaries And Daily Upgrades You Need To Make Them Stick',
        imageUrl: 'https://cdn01.sapnaonline.com/product_media/9781529367157/md_9781529367157_020220231400231.jpg',
        description: "At SapnaOnline.com we are working towards bringing our retail experience to the web and we strive to uphold this prestige by serving our customers better.",
        price: 250,
      },
    ],
  },
  {
    title: 'pets',
    items: [
      {
        id: 1,
        name: 'Cocker Spaniel Puppies',
        imageUrl: 'https://www.marshallspetzone.com/2918-home_default/cocker-spaniel-puppies-for-sale.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 25000,
      },
      {
        id: 2,
        name: 'Great Dane Puppies',
        imageUrl: 'https://www.marshallspetzone.com/2910-home_default/great-dane-puppies-for-sale.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 18000,
      },
      {
        id: 3,
        name: 'Beagle Puppies',
        imageUrl: 'https://www.marshallspetzone.com/6736-home_default/beagle-puppies-for-sale.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 35000,
      },
      {
        id: 4,
        name: 'Siberian Husky Puppies',
        imageUrl: 'https://www.marshallspetzone.com/21917-home_default/siberian-husky-puppies-for-sale.jpg',
        description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        price: 25,
      },
    ],
  },
];
export const CATEGORY = [
  {
    id: 1,
    title: 'Mobiles',
    slug: 'mobiles',
    imageUrl: 'https://i.ibb.co/cvpntL1/mobiles.png',
  },
  {
    id: 2,
    title: 'Bikes',
    slug: 'bikes',
    imageUrl: 'https://i.ibb.co/px2tCc3/bikes.png',
  },
  {
    id: 3,
    title: 'Electronics-Appliances',
    slug: 'electronics-applicances',
    imageUrl: 'https://i.ibb.co/0jqHpnp/electronics.png',
  },
  {
    id: 4,
    title: 'Furniture',
    slug: 'furniture',
    imageUrl: 'https://i.ibb.co/GCCdy8t/furniture.png',
  },
  {
    id: 5,
    title: 'Fashion',
    slug: 'fashion',
    imageUrl: 'https://i.ibb.co/R70vBrQ/fashion.png',
  },
  {
    id: 6,
    title: 'Books',
    slug: 'books',
    imageUrl: 'https://i.ibb.co/R70vBrQ/books.png',
  },
  {
    id: 7,
    title: 'Pets',
    slug: 'pets',
    imageUrl: 'https://i.ibb.co/R70vBrQ/pets.png',
  },
];
